<a href="https://colab.research.google.com/github/Keerthzzzz/YBI-Foundation-Internship/blob/main/Women_Clothes_Review.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
df=pd.read_csv(r'/content/Womens Clothing E-Commerce Reviews.csv')

In [4]:
df.head()

Unnamed: 0  Clothing ID  Age                    Title  \
0           0          767   33                      NaN   
1           1         1080   34                      NaN   
2           2         1077   60  Some major design flaws   
3           3         1049   50         My favorite buy!   
4           4          847   47         Flattering shirt   

                                         Review Text  Rating  Recommended IND  \
0  Absolutely wonderful - silky and sexy and comf...       4                1   
1  Love this dress!  it's sooo pretty.  i happene...       5                1   
2  I had such high hopes for this dress and reall...       3                0   
3  I love, love, love this jumpsuit. it's fun, fl...       5                1   
4  This shirt is very flattering to all due to th...       5                1   

   Positive Feedback Count   Division Name Department Name Class Name  
0                        0       Initmates        Intimate  Intimates  
1                        4         General         Dresses    Dresses  
2                        0         General         Dresses    Dresses  
3                        0  General Petite         Bottoms      Pants  
4                        6         General            Tops    Blouses

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23486 entries, 0 to 23485
Data columns (total 11 columns):
 #   Column                   Non-Null Count  Dtype 
---  ------                   --------------  ----- 
 0   Unnamed: 0               23486 non-null  int64 
 1   Clothing ID              23486 non-null  int64 
 2   Age                      23486 non-null  int64 
 3   Title                    19676 non-null  object
 4   Review Text              22641 non-null  object
 5   Rating                   23486 non-null  int64 
 6   Recommended IND          23486 non-null  int64 
 7   Positive Feedback Count  23486 non-null  int64 
 8   Division Name            23472 non-null  object
 9   Department Name          23472 non-null  object
 10  Class Name               23472 non-null  object
dtypes: int64(6), object(5)
memory usage: 2.0+ MB


In [6]:
df.shape

(23486, 11)

In [7]:
#remove missing values in Reviews columns with No Review text
df.isna().sum()

Unnamed: 0                    0
Clothing ID                   0
Age                           0
Title                      3810
Review Text                 845
Rating                        0
Recommended IND               0
Positive Feedback Count       0
Division Name                14
Department Name              14
Class Name                   14
dtype: int64

In [8]:
df[df['Review Text']==""]=np.NaN

In [9]:
df['Review Text'].fillna("No Review",inplace=True)

In [10]:
df.isna().sum()

Unnamed: 0                    0
Clothing ID                   0
Age                           0
Title                      3810
Review Text                   0
Rating                        0
Recommended IND               0
Positive Feedback Count       0
Division Name                14
Department Name              14
Class Name                   14
dtype: int64

In [11]:
df['Review Text']

0        Absolutely wonderful - silky and sexy and comf...
1        Love this dress!  it's sooo pretty.  i happene...
2        I had such high hopes for this dress and reall...
3        I love, love, love this jumpsuit. it's fun, fl...
4        This shirt is very flattering to all due to th...
                               ...                        
23481    I was very happy to snag this dress at such a ...
23482    It reminds me of maternity clothes. soft, stre...
23483    This fit well, but the top was very see throug...
23484    I bought this dress for a wedding i have this ...
23485    This dress in a lovely platinum is feminine an...
Name: Review Text, Length: 23486, dtype: object

Define Target(y) and Feature(X)

In [12]:
df.columns

Index(['Unnamed: 0', 'Clothing ID', 'Age', 'Title', 'Review Text', 'Rating',
       'Recommended IND', 'Positive Feedback Count', 'Division Name',
       'Department Name', 'Class Name'],
      dtype='object')

In [13]:
X=df['Review Text']

In [14]:
y=df['Rating']

In [ ]:
df['Rating'].value_counts()

In [15]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.7,random_state=112529)
X_train.shape,X_test.shape,y_train.shape,y_test.shape

((7045,), (16441,), (7045,), (16441,))

In [16]:
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer(lowercase=True,analyzer='word',ngram_range=(2,3),stop_words='english',max_features=5000)

In [17]:
X_train=cv.fit_transform(X_train)

In [18]:
cv.get_feature_names_out()

array(['00p 0p', '10 10', '10 12', ..., 'yellow color', 'yesterday store',
       'yoga pants'], dtype=object)

In [19]:
X_train.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [20]:
X_test=cv.fit_transform(X_test)

In [21]:
cv.get_feature_names_out()

array(['00 petite', '0p fit', '10 12', ..., 'years old', 'yellow color',
       'yoga pants'], dtype=object)

In [22]:
X_test.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [23]:
from sklearn.naive_bayes import MultinomialNB
model=MultinomialNB()
model.fit(X_train,y_train)

MultinomialNB()

In [24]:
y_pred=model.predict(X_test)
y_pred.shape

(16441,)

In [25]:
y_pred

array([4., 3., 3., ..., 5., 2., 3.])

probability of each predicted class

In [26]:
model.predict_proba(X_test)

array([[0.03853872, 0.06693227, 0.31032718, 0.55651268, 0.02768915],
       [0.09794795, 0.04817084, 0.63120078, 0.16144039, 0.06124004],
       [0.07194878, 0.0892435 , 0.58429619, 0.19927967, 0.05523186],
       ...,
       [0.1229292 , 0.03883438, 0.24984108, 0.02852038, 0.55987495],
       [0.13767463, 0.83008183, 0.02344273, 0.00483625, 0.00396456],
       [0.05424135, 0.37375707, 0.5319947 , 0.03048633, 0.00952055]])

Model Evaluation

In [27]:
from sklearn.metrics import confusion_matrix,classification_report
print(confusion_matrix(y_test,y_pred))

[[  31   37   65  142  307]
 [  79   88  145  247  524]
 [ 139  195  285  460  916]
 [ 318  377  472  766 1650]
 [ 899  848 1108 1795 4548]]


In [28]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

         1.0       0.02      0.05      0.03       582
         2.0       0.06      0.08      0.07      1083
         3.0       0.14      0.14      0.14      1995
         4.0       0.22      0.21      0.22      3583
         5.0       0.57      0.49      0.53      9198

    accuracy                           0.35     16441
   macro avg       0.20      0.20      0.20     16441
weighted avg       0.39      0.35      0.37     16441



CATEGORIZE RATINGS AS POOR(0) AND GOOD(1)

In [29]:
df['Rating'].value_counts()

5.0    13131
4.0     5077
3.0     2871
2.0     1565
1.0      842
Name: Rating, dtype: int64

In [30]:
#Re-Rating 1,2,3 as 0 and 4,5 as 1
df.replace({'Rating':{1:0,2:0,3:0,4:1,5:1}},inplace=True)

In [31]:
y=df['Rating']
X=df['Rating']

In [32]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.7,random_state=112529)
X_train.shape,X_test.shape,y_train.shape,y_test.shape

((7045,), (16441,), (7045,), (16441,))

In [33]:
from sklearn.feature_extraction.text import CountVectorizer

In [34]:
cv=CountVectorizer(lowercase=True,analyzer='word',ngram_range=(2,3),stop_words='english',max_features=5000)

In [ ]:
X_train=cv.fit_transform(X_train)

In [ ]:
X_test=cv.fit_transform(X_test)

Re-train Model

In [ ]:
from sklearn.naive_bayes import MultinomialNB
model=MultinomialNB()
model.fit(X_train,y_train)

In [ ]:
y_pred=model.predict(X_test)

In [ ]:
y_pred.shape

In [ ]:
y_pred

Model Evaluation

In [ ]:
from sklearn.metrics import confusion_matrix,classification_report

In [ ]:
print(confusion_matrix(y_train,y_pred))

In [ ]:
print(classification_report(y_train,y_pred))